import { AlertTriangle } from "lucide-react";
import LegalPageLayout from "@/components/legal/LegalPageLayout";

export default function Disclaimer() {
  return (
    <LegalPageLayout
      title="Disclaimer"
      subtitle="Important information about the use of AI-generated content and our Service."
      icon={<AlertTriangle />}
      metaTitle="Disclaimer — Growvix By Offdx"
      metaDescription="Important disclaimers about AI-generated content, third-party platforms, and the use of Growvix."
    >
      <p><em>Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</em></p>

      <h2>1. General Information</h2>
      <p>
        The information and content provided by <strong>Growvix By Offdx</strong> is
        for general use only. While we strive for accuracy and quality, we make no
        representations or warranties of any kind, express or implied, about completeness,
        reliability, suitability, or availability of the Service or the AI-generated
        content.
      </p>

      <div className="my-6 rounded-2xl border border-primary/30 bg-primary/5 p-5">
        <h3 className="text-base font-semibold text-foreground mb-1">📌 AI-Generated Content</h3>
        <p className="text-sm text-muted-foreground m-0">
          All content produced by Growvix's AI is generated automatically and may
          contain inaccuracies, outdated information, or unintended phrasing. <strong className="text-foreground">
          You are solely responsible</strong> for reviewing, editing, and approving content
          before publishing.
        </p>
      </div>

      <h2>2. No Professional Advice</h2>
      <p>
        Content generated by Growvix is <strong>not</strong> a substitute for
        professional marketing, legal, financial, medical, or business advice. Always
        consult qualified professionals for advice specific to your situation.
      </p>

      <h2>3. Third-Party Platforms</h2>
      <p>
        Growvix publishes to third-party platforms (Facebook, Instagram, LinkedIn, X,
        Google Business, etc.). We are not affiliated with, endorsed by, or responsible
        for:
      </p>
      <ul>
        <li>Changes in third-party APIs or policies that may affect publishing</li>
        <li>Account suspensions, restrictions, or content removals by these platforms</li>
        <li>Downtime, data loss, or feature deprecation on third-party services</li>
      </ul>

      <h2>4. Results & Performance</h2>
      <p>
        We do not guarantee specific business results, follower growth, engagement rates,
        or revenue from using Growvix. Outcomes depend on many factors outside our
        control including your industry, audience, and content quality.
      </p>

      <h2>5. External Links</h2>
      <p>
        Our Service may contain links to external websites. We are not responsible for
        the content, privacy practices, or accuracy of any third-party sites.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        Growvix, Offdx, and its team shall not be held liable for any losses, damages,
        or claims arising from the use, misuse, or inability to use the Service or its
        AI-generated content.
      </p>

      <h2>7. Compliance Responsibility</h2>
      <p>
        You are responsible for ensuring that your use of the Service and the content you
        publish complies with all applicable laws, advertising standards, and platform
        community guidelines in your jurisdiction.
      </p>

      <h2>8. Changes to this Disclaimer</h2>
      <p>
        We may update this Disclaimer at any time. Continued use of the Service after
        changes constitutes acceptance of the revised terms.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions? Email us at{" "}
        <a href="mailto:support@growvix.offdx.in">support@growvix.offdx.in</a>.
      </p>
    </LegalPageLayout>
  );
}
