import { FileText } from "lucide-react";
import LegalPageLayout from "@/components/legal/LegalPageLayout";

export default function TermsConditions() {
  return (
    <LegalPageLayout
      title="Terms & Conditions"
      subtitle="The rules and agreements that govern your use of SocioPilot."
      icon={<FileText />}
      metaTitle="Terms & Conditions — SocioPilot By Offdx"
      metaDescription="Read the terms and conditions for using SocioPilot, an AI-powered social media automation platform by Offdx."
    >
      <p><em>Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</em></p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using SocioPilot ("Service"), operated by <strong>Offdx</strong>
        (GSTIN: 20DCSPM1849C1ZP, registered in Dhanbad, Jharkhand, India), you agree
        to be bound by these Terms & Conditions. If you do not agree, please do not use
        the Service.
      </p>

      <h2>2. Service Description</h2>
      <p>
        SocioPilot is a <strong>SaaS subscription platform</strong> that provides AI-powered
        content generation, scheduling, and publishing tools for social media. Service is
        offered on a monthly or annual subscription basis.
      </p>

      <h2>3. Account & Eligibility</h2>
      <ul>
        <li>You must be at least 18 years old to use the Service.</li>
        <li>You are responsible for maintaining the confidentiality of your account.</li>
        <li>One business profile is allowed per user account.</li>
        <li>Mobile OTP verification is required for new accounts.</li>
      </ul>

      <h2>4. Subscription & Billing</h2>
      <ul>
        <li>Subscriptions auto-renew at the end of each billing cycle unless cancelled.</li>
        <li>Pricing is region-based: Indian users are billed in <strong>INR (₹)</strong> via Cashfree; international users in <strong>USD ($)</strong> via Stripe.</li>
        <li>All Indian transactions are subject to applicable <strong>GST</strong>.</li>
        <li>International payments comply with FEMA and applicable cross-border regulations.</li>
      </ul>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Generate or publish unlawful, hateful, harassing, or misleading content</li>
        <li>Infringe on intellectual property rights of others</li>
        <li>Reverse engineer, scrape, or abuse our APIs and infrastructure</li>
        <li>Bypass usage limits, plan restrictions, or security controls</li>
      </ul>

      <h2>6. AI-Generated Content</h2>
      <p>
        Content generated by our AI is provided "as-is." You are solely responsible for
        reviewing, editing, and ensuring suitability before publishing. SocioPilot does
        not guarantee accuracy, originality, or fitness for any particular purpose.
      </p>

      <h2>7. Third-Party Platforms</h2>
      <p>
        Publishing to Facebook, Instagram, LinkedIn, X, and other platforms requires you
        to grant access tokens. We are not liable for changes, downtime, or policy
        violations on third-party platforms.
      </p>

      <h2>8. Termination</h2>
      <p>
        We may suspend or terminate your account for violation of these terms. You may
        cancel your subscription at any time from your account settings. Upon deletion,
        your data is purged per our Privacy Policy.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Offdx shall not be liable for indirect,
        incidental, or consequential damages arising from use of the Service. Our total
        liability is limited to the amount paid by you in the preceding 3 months.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These terms are governed by the laws of India. Disputes shall be subject to the
        exclusive jurisdiction of the courts of Dhanbad, Jharkhand.
      </p>

      <h2>11. Contact</h2>
      <p>
        For questions, email us at{" "}
        <a href="mailto:support@sociopilot.in">support@sociopilot.in</a>.
      </p>
    </LegalPageLayout>
  );
}
